title = "Alan"
baseURL = "https://alany1.github.io/"
languageCode = "en-us"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLS = true

[languages]
  [languages.en]
    title = "About"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  #[languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  #description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 0
  mainSections=[' ']

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
